### ISSUE TITLE
Use a cache to speed up calculations

### ISSUE THREAD

**Issue by Nyholm** [bmitch/churn-php#187]
I just started to use this library. I have not looked into the source yet so Im sorry if I ask a weird question. 

Would it be possible to use a cache to speed up execution? 
What if the cache contained complexity and changes for every file in my project up until yesterday. Then when I do `churn run src` I will only calculate the change set between yesterday and now.

**Comment by bmitch** [comment]
Thank you for the suggestion @Nyholm 

It does sound like a good idea but a couple of notes:
* I think most people run this during a CI pipeline which probably would not have access to a cache since every run via the pipeline is essentially fresh. However, if you are running this locally over and over then a cache could be helpful.
* If you are looking for a way to increase the performance you could limit how far back in the git history it looks. See https://github.com/bmitch/churn-php#how-to-configure and the `commitsSince`. Perhaps that will solve your issue?

Are you having poor performance using this tool? If so please feel free to open another issue with details. Thanks!

**Comment by villfa** [comment]
A cache will be available from the next release (1.5.0).
