### ISSUE TITLE
Cannot run the tool locally

### ISSUE THREAD

**Issue by gnutix** [bmitch/churn-php#219]
I've tried running the `dev-master` version of the tool on my machine (PHP 7.4, installed globally via Composer) directly (`churn run [path]`) on a medium, small and finally very small folder of PHP code files and got no result whatsoever except a 99% CPU and zero output (related to #199 and #210). "Is it just me" ?

However, it worked with the Docker box running `docker run --rm -ti -v $PWD:/app dockerizedphp/churn run [path]`

**Comment by bmitch** [comment]
Thanks @gnutix, and sorry you're having troubles. Unfortunately I have minimal time at the moment to dedicate to this project so won't be able to assist. Perhaps there might be others who could help.

**Comment by gnutix** [comment]
That's alright as I managed to run it via Docker. I would just keep it open if others have a similar issue so they can comment here, if that's ok to you.

**Comment by villfa** [comment]
The problem came from 953e0fb4013d515463b4842a5562bf15047582ed and was only visible on `dev-master`.
The *git* commands failed silently and *churn* was blocked in an infinite loop.

Since it is now fixed by 3e9793b6e9ea873be34871063940fa3d308200cc I close this issue.
Please reopen it if you observe the same issue again.
